homeassistant:
  # Name of the location where Home Assistant is running
  name: Proteus
  # Location required to calculate the time the sun rises and sets
  latitude: !secret base_lat
  longitude: !secret base_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 21
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  customize: !include includes/customize.yaml

# Show links to resources in log and frontend
#introduction:
config:
# Enables the frontend
frontend:
# Checks for available updates
updater:
# Discover some devices automatically
discovery:
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
# Enables support for tracking state changes over time.
history:
# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.housesmtp  
# Track the sun		
sun:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_api_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret http_base_url
  #ip_ban_enabled: True
  login_attempts_threshold: 5
  ip_ban_enabled: True

logger:
  default: warn
  logs:
    homeassistant.components.device_tracker: warn
    homeassistant.components.media_player: warn
    #homeassistant.components.mqtt: debug

device_tracker:
  - platform: bluetooth_tracker
  - platform: nmap_tracker
    hosts: 192.168.1.1-200
    home_interval: 10
  - platform: asuswrt
    host: 192.168.1.1
    username: !secret asus_username
    password: !secret asus_password
    protocol: ssh
  - platform: ping
    hosts:
      Modem: 10.0.0.1
#    scan_options: " -sP "
#    scan_options: " -sP --host-timeout 5s"

tts:
  platform: google


#cal
google:
  client_id: !secret gcal_client_id
  client_secret: !secret gcal_client_secret

ifttt:
  key: !secret ifttt_key

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

mqtt: 

media_player:
  - platform: mpd
    host: 192.168.1.208
    name: MusicBox
  - platform: mpd
    host: 192.168.1.202
    name: Studio
  - platform: snapcast
    host: 192.168.1.208
    
notify:
  - name: email_stephen
    platform: smtp
    server: smtp.gmail.com
    port: 587
    sender: !secret smtp_username
    starttls: true
    username: !secret smtp_username
    password: !secret smtp_password
    recipient: !secret email_s2
  - name: email_anna
    platform: smtp
    server: smtp.gmail.com
    port: 587
    sender: !secret smtp_username
    starttls: true
    username: !secret smtp_username
    password: !secret smtp_password
    recipient: !secret email_a1
  - name: email_both
    platform: group
    services:
      - service: email_stephen
      - service: email_anna
 
##########################
# Includes
##########################
alexa:
intent_script: !include includes/alexa.yaml
binary_sensor: !include includes/binary_sensor.yaml
sensor: !include includes/sensors.yaml
#https://community.home-assistant.io/t/update-config-automatically-if-travis-ci-build-succeeds/19966
automation: !include_dir_merge_list automation/
script: !include includes/scripts.yaml
group: !include includes/groups.yaml
switch: !include includes/switch.yaml
#scene: !include includes/scenes.yaml
#input_boolean: !include includes/inputs.yaml
shell_command: !include includes/shell_commands.yaml

##########################
#zones
##########################
zone:
  name: Work
  latitude: 51.5108172
  longitude: -0.082078
  radius: 250
  icon: mdi:worker

zone 1:
  name: Tate Modern
  latitude: 51.5075953
  longitude: -0.1015451
  radius: 100
  icon: mdi:factory

zone 2:
  name: Tate Britain
  latitude: 51.4910621
  longitude: -0.1299773
  radius: 100
  icon: mdi:worker

