- alias: 'Update config if travis build is successfull'
  trigger:
    platform: state
    entity_id: sensor.travis_build_label
  condition:
    - condition: state
      entity_id: sensor.travis_status
      state: 'Success'
  action:
    - service: script.get_latest_config

#- alias: 'Alert on piano ant fail'
#  trigger:
#    platform: numeric_state
#    entity_id: sensor.piano_ant
#    value_template: "{{ state.attributes }}"
#    below: 1
#  action:
#    - service: notify.email_stephen
#      data:
#        message: check the piano

################################
#home/away
################################

- alias: 'Away Mode'
  trigger:
    platform: state
    entity_id: group.main_people
    from: 'home'
    to: 'not_home'
    for:
      minutes: 15
  action:
    - service: homeassistant.turn_off
      entity_id: switch.u3_switch
    - service: homeassistant.turn_off
      entity_id: switch.musicbox_amp
    - service: homeassistant.turn_off
      entity_id: switch.studio_amp
    - service: nest.set_mode
      data:
        home_mode: away
    - service: media_player.media_pause
      entity_id: media_player.musicbox
    - service: media_player.media_pause
      entity_id: media_player.studio

- alias: 'Home Mode'
  trigger:
    platform: state
    entity_id: group.main_people
    to: 'home'
  action:
    - service: nest.set_mode
      data:
        home_mode: home

################################
#lights
################################

#this can be cancelled?
- alias: 'Lamp off if late'
  trigger:
  - platform: time
    at: '00:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.u3_switch

- alias: 'Lamp on at home at night'
  trigger:
    platform: sun
    event: sunset
    offset: '00:00:00'
  condition:
    # Prefix the first line of each condition configuration
    # with a '-'' to enter multiple
    - condition: state
      entity_id: group.main_people
      state: 'home'
  action:
    service: homeassistant.turn_on
    entity_id: switch.u3_switch

- alias: 'Lamp off if no motion for a time'
  trigger:
  - platform: state
    entity_id: binary_sensor.pir_hallway
    to: 'off'
    for:
      minutes: 15
  action:
    service: homeassistant.turn_off
    entity_id: switch.u3_switch

- alias: 'Lamp on if motion after sunset'
  trigger:
  - platform: state
    entity_id: binary_sensor.pir_hallway
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    service: homeassistant.turn_on
    entity_id: switch.u3_switch

################################
#media
################################
- alias: 'Amps on if Musicbox on'
  trigger:
    platform: state
    entity_id: media_player.musicbox
    to: 'playing'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.musicbox_amp
    - service: homeassistant.turn_on
      entity_id: switch.studio_amp

- alias: 'Amps off if Musicbox off'
  trigger:
    platform: state
    entity_id: media_player.musicbox
    from: 'playing'
    to: 'paused'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.musicbox_amp
    - service: homeassistant.turn_off
      entity_id: switch.studio_amp

#- alias: 'Play Fip'
#  trigger:
#    platform: state
#    entity_id: group.main_people
#    to: 'home'
#  condition:
    # Prefix the first line of each condition configuration
    # with a '-'' to enter multiple
#    - condition: time
#      after: '16:00:00'
#      before: '22:00:00'
#  action:
#    service: media_player.select_source
#    entity_id: media_player.musicbox
#    data:
#      source: 'fip'
