- alias: 'Update config if travis build is successfull'
  trigger:
    platform: state
    entity_id: sensor.travis_build_label
  condition:
    - condition: state
      entity_id: sensor.travis_status
      state: 'Success'
  action:
    - service: script.get_latest_config

- alias: 'Alert on piano ant fail'
  trigger:
    platform: state
    entity_id: sensor.piano_ant
  condition:
    - condition: state
      entity_id: sensor.piano_ant
      state: 0
  action
    - service: notify.email_stephen
      data:
        message: check the piano
