- platform: iss
- platform: rest
  name: Travis Status
  resource: https://api.travis-ci.org/repos/photoangell/ProteusConfig/cc.json?branch=master
  scan_interval: 60
  value_template: "{{ value_json.last_build_status|int(1) == 0 }}"
#- platform: rpi_gpio
#  ports:
#    21: pir_hallway
